Add versions to crates.io patches
Without this running `cargo build` in the top-level directory on nightly
produced an error for me:

```
error: failed to resolve patches for `https://github.com/rust-lang/crates.io-index`

Caused by:
  patch for `wasm-bindgen-futures` in `https://github.com/rust-lang/crates.io-index` did not resolve to any crates. If this is unexpected, you may wish to consult: https://github.com/rust-lang/cargo/issues/4678
```